### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by TPXP** [ineentho/fastlane-docker#1]
Hello,

Thank you for your incredible work, I managed to upload my app to TestFlight! I have a few remarks:
* Do you really need xar ? I used it because I worked with the OSX installer, but since you have an exe file it is probably not needed (I see you use p7zip)
* Installing an headless JRE will save some space (it won't install a ton of graphical libraries)
* Will you publish your image to the docker hub?

Thanks again! If you want, I can open a pull request

Thomas

**Comment by ineentho** [comment]
Thanks for your suggestions! To be honest, I didn't even bother to check what xar did, but yea, we'll probably only need one of 7zip and xar.

Yes, I want to fix this docker image to be more of "production quality"  and publish it to Dockerhub. I usually prefer to build my docker images using alpine, so I might give that a try. I don't think the alpine version of open jre installs any graphical stuff by default.

If you want to, please submit a PR, otherwise I'll fix it myself in a few days

**Comment by TPXP** [comment]
I opened #2 and #3 to get a smaller image.

I noticed you commented [the line where you actually install fastlane](https://github.com/ineentho/fastlane-docker/blob/master/Dockerfile#L81):
```dockerfile
# RUN gem install fastlane
```
Shouldn't fastlane be included in the image?
